apiVersion: authorino.kuadrant.io/v1beta2
kind: AuthConfig
metadata:
  labels:
    security.opendatahub.io/authorization-group: default
spec:
  hosts:
  - "UPDATED.RUNTIME"
  authentication:
    kubernetes-user:
      credentials:
        authorizationHeader: {}
      kubernetesTokenReview:
        audiences:
        - https://kubernetes.default.svc

  authorization:
    kubernetes-rbac:
      kubernetesSubjectAccessReview:
        resourceAttributes:
          verb:
            value: get
          group:
            value: serving.kserve.io/v1beta1
          resource:
            value: inferenceservice
          namespace:
            value: {{ .Namespace }}
        user:
          selector: auth.identity.user.username