apiVersion: authorino.kuadrant.io/v1beta2
kind: AuthConfig
metadata:
  labels:
    security.opendatahub.io/authorization-group: default
spec:
  hosts:
  - "example.com"
  authentication:
    kubernetes-user:
      credentials:
        authorizationHeader: {}
      kubernetesTokenReview:
        audiences:
        - https://kubernetes.default.svc
  response:
    unauthenticated:
      code: 302
      headers:
        Location:
          selector: http://some-service?redirect_to={context.request.http.path}
    unauthorized:
      code: 403
      headers:
        Location:
          selector: http://some-service?redirect_to={context.request.http.path}
